backend:
  name: github
  repo: emmettokay/emmettokay.github.io
  branch: main
  auth_endpoint: https://github.com/login/oauth/authorize

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: "thoughts"
    label: "My (Briefer) Thoughts"
    folder: "content/thoughts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
