backend:
  name: git-gateway
  branch: main  # Adjust if your default branch is not 'main'

media_folder: static/img/uploads  # Folder in your repo for uploaded images
public_folder: /img/uploads  # Folder for public image access

collections:
  - name: "thoughts"
    label: "My (Briefer) Thoughts"
    folder: "content/thoughts"  # Folder where thoughts are stored
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Post URL format
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", default: "now" }
      - { label: "Body", name: "body", widget: "markdown" }
