name: Deploy CMS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Inject OAuth Credentials
        run: |
          echo "client_id: ${{ secrets.OAUTH_CLIENT_ID }}" > admin/secrets.yml
          echo "client_secret: ${{ secrets.OAUTH_CLIENT_SECRET }}" >> admin/secrets.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./admin
